
server: 
  port: 8763

spring: 
  application: 
    name: registry
  datasource: 
    url: jdbc:mysql://localhost:3306/prod
    username: root
    password: root

mybatis: 
  type-aliases-package: com.test.registry.entity
  mapper-locations: classpath:mapper/*.xml

eureka: 
  instance: 
    hostname: localhost
  client: 
    serviceUrl: 
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
